// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9XHf4NEH31GwZyJrGxmU8TZXJWOOqyQ',
    appId: '1:339208394757:web:28fe22930ffbc4368ae46c',
    messagingSenderId: '339208394757',
    projectId: 'resiwash-ed0c2',
    authDomain: 'resiwash-ed0c2.firebaseapp.com',
    storageBucket: 'resiwash-ed0c2.firebasestorage.app',
    measurementId: 'G-ZKWDSDGC77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiHODfVwSWKsw5APPbROKySA-9NMgBx8',
    appId: '1:339208394757:android:493bd9f5f52d2c108ae46c',
    messagingSenderId: '339208394757',
    projectId: 'resiwash-ed0c2',
    storageBucket: 'resiwash-ed0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Aq4NMnEme3iSXZ9LSpNVgv_Uc8w1ggQ',
    appId: '1:339208394757:ios:d3af122777a049c78ae46c',
    messagingSenderId: '339208394757',
    projectId: 'resiwash-ed0c2',
    storageBucket: 'resiwash-ed0c2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
