name: resiwash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^16.1.0
  google_fonts: ^6.2.1
  json_annotation: ^4.0.1
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  build_test: any

flutter:
  uses-material-design: true
  assets:
    - assets/dryer.svg
    - assets/washer.svg

